package com.facebook.presto.operator.aggregation.lambda;

import com.facebook.presto.spi.ConnectorSession;
import com.facebook.presto.sql.gen.lambda.BinaryFunctionInterface;

public class ToyLambdaChannelProvider implements LambdaChannelProvider
{
    private final ConnectorSession session;

    public ToyLambdaChannelProvider(ConnectorSession session)
    {
        this.session = session;
    }

    public Object getLambda()
    {
        // This will be actually generated by invokedynamic
        return new BinaryFunctionInterface() {
            @Override
            public Object apply(Object arg1, Object arg2)
            {
                return (long) arg1 * (long) arg2;
            }
        };
    }
}
