package com.facebook.presto.operator.aggregation.lambda;

import com.facebook.presto.spi.ConnectorSession;
import com.facebook.presto.sql.gen.lambda.BinaryFunctionInterface;

public class ToyLambdaChannelProvider implements LambdaChannelProvider
{
    // To support capture, need to enrich the interface into
    // getLambda(ConnectorSession session, Object[] capturedValues)
    public Object getLambda(ConnectorSession session)
    {
        // This will be actually generated by invokedynamic
        return new BinaryFunctionInterface() {
            @Override
            public Object apply(Object arg1, Object arg2)
            {
                return (int) arg1 + (int) arg2;
            }
        };
    }
}
